export const INTROLOADER_UNMOUNGTED = "INTROLOADER_UNMOUNGTED";
export const LOBBY_SECOND_LOADER_CLOSE = "LOBBY_SECOND_LOADER_CLOSE";
export const SET_LOBBY_LOADER_READY = "SET_LOBBY_LOADER_READY";
export const SET_FILTERED_ALERTLIST = "SET_FILTERED_ALERTLIST";
export const FIRST_VALIDATION_RUNNED = "FIRST_VALIDATION_RUNNED";

export const OPEN_STAMP = "OPEN_STAMP";
export const CLOSE_STAMP = "CLOSE_STAMP";
export const TOGGLE_EVENTLIST = "TOGGLE_EVENTLIST";

export const OPEN_SURVEY = "OPNE_SURVEY";
export const CLOSE_SURVEY = "CLOSE_SURVEY";

export const LAZYLOAD_NAVBAR = "LAZYLOAD_NAVBAR";
export const OPEN_NAVBAR = "OPEN_NAVBAR";
export const CANCEL_DELAY_NAVBAR = "CANCEL_DELAY_NAVBAR";

export const TOGGLE_INFO = "TOGGLE_INFO";
export const FETCH_ALERT = "FETCH_ALERT";

// loader reducer
export const INTROLOADBAR_UNMOUNTED = "INTROLOADBAR_UNMOUNTED";
export const CLOSE_ROOM_LOADER = "CLOSE_ROOM_LOADER";
export const OPEN_ROOM_LOADER = "OPEN_ROOM_LOADER";
export const LOBBY_LOADBAR_WILLMOUNT = "LOBBY_LOADBAR_WILLMOUNT";

// alert

export const OPEN_ONE_TO_ONE_CHAT = "OPEN_ONE_TO_ONE_CHAT";
export const CLOSE_ONE_TO_ONE_CHAT = "CLOSE_ONE_TO_ONE_CHAT";

export const OPEN_ALERT_AND_SET_ITS_CONTENT = "OPEN_ALERT_AND_SET_ITS_CONTENT";
export const HANDLE_OPEN_JOINALERT = "HANDLE_OPEN_JOINALERT";
export const HANDLE_CLOSE_JOINALERT = "HANDLE_CLOSE_JOINALERT";
export const CLOSE_ALERT_AND_DELETE_ITS_CONTENT =
  "CLOSE_ALERT_AND_DELETE_ITS_CONTENT";

// opener
export const CLOSE_UPRISM_GUIDE = "CLOSE_UPRISM_GUIDE";
export const OPEN_UPRISM_GUIDE = "OPEN_UPRISM_GUIDE";
export const CLOSE_RESPONSE_ALERT = "CLOSE_RESPONSE_ALERT";
export const OPEN_RESPONSE_ALERT = "OPEN_RESPONSE_ALERT";
export const TOGGLE_GUIDE_MODAL = "TOGGLE_GUIDE_MODAL";
export const TOGGLE_TECH_SUPPORT = "TOGGLE_TECH_SUPPORT";

// conference
export const SET_CURRENT_CONTENT = "SET_CURRENT_CONTENT";
export const SET_CONTENTS = "SET_CONTENTS";
export const TOGGLE_CONFERENCE_MODAL = "TOGGLE_CONFERENCE_MODAL";
export const ON_LEAVE_CONFERENCE_ROOM = "ON_LEAVE_CONFERENCE_ROOM";
